server {
    listen 80;
    server_name cnimuy.site;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name cnimuy.site;

    ssl_certificate /etc/letsencrypt/live/cnimuy.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cnimuy.com/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /static {
        alias /static;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}